### ISSUE TITLE
bigip_selfip - cannot create a self IP in a particular partition

### ISSUE THREAD

**Issue by payalsin** [F5Networks/f5-ansible#229]
I have a partition on the BIG-IP "Tenant1A". I was trying to create a self IP inside that partition. 

Got the following error:

'''
---
- name: Onboarding BIG-IP
  hosts: bigip
  gather_facts: false

  tasks:

  - name: Configure SELF-IPs on the BIG-IP
    bigip_selfip:
     server: "10.192.73.218"
     user: "admin"
     password: "admin"
     validate_certs: False
     name: "selfip"
     address: "10.10.10.10"
     netmask: "255.255.255.0"
     vlan: "External"
     partition: "Tenant1A"
    delegate_to: localhost

----------------------------

TASK [Configure SELF-IPs on the BIG-IP] *****************************************************************************************************************************************************************************************************
fatal: [10.192.73.218 -> localhost]: FAILED! => {"changed": false, "failed": true, "msg": "400 Unexpected Error: Bad Request for uri: https://10.192.73.218:443/mgmt/tm/net/self/\nText: u'{\"code\":400,\"message\":\"01070734:3: Configuration error: Traffic group (/Tenant1A/traffic-group-local-only) does not exist.\",\"errorStack\":[],\"apiError\":3}'"}

So then I added the traffic group to point to the one in Common parition, but I got the following error:

- name: Configure SELF-IPs on the BIG-IP
    bigip_selfip:
     server: "10.192.73.218"
     user: "admin"
     password: "admin"
     validate_certs: False
     name: "selfip"
     address: "10.10.10.10"
     netmask: "255.255.255.0"
     vlan: "External"
     partition: "Tenant1A"
     traffic_group: "/Common/traffic-group-local-only"
    delegate_to: localhost

fatal: [10.192.73.218 -> localhost]: FAILED! => {"changed": false, "failed": true, "msg": "The specified traffic group was not found"}

**Comment by caphrim007** [comment]
@payalsin try now

**Comment by caphrim007** [comment]
@payalsin is this still an issue?

**Comment by payalsin** [comment]
@caphrim007 - issue is resolved with respect to the traffic_group. But the same issue is present for VLAN.

If the VLAN is in the partition then no error. If the VLAN is in the common partition then there is an error (It is always looking for the VLAN to be in the same partition)

bigip_selfip:
server: "10.192.73.218"
user: "admin"
password: "admin"
validate_certs: False
name: "selfip"
address: "10.10.10.10"
netmask: "255.255.255.0"
vlan: "/Common/External"
partition: "Tenant1A"
traffic_group: "/Common/traffic-group-local-only"
delegate_to: localhost

fatal: [10.192.73.218 -> localhost]: FAILED! => {"changed": false, "failed": true, "msg": "400 Unexpected Error: Bad Request for uri: https://10.192.73.218:443/mgmt/tm/net/self/\nText: u'{\"code\":400,\"message\":\"01070277:3: The requested vlan, vlangroup or tunnel (/Tenant1A/Common/External) was not found.\",\"errorStack\":[],\"apiError\":3}'"}

**Comment by caphrim007** [comment]
@payalsin ok, one sec. lemme fix vlan

**Comment by caphrim007** [comment]
@payalsin I believe the updated code should solve this problem now. Lemme know if it does not

**Comment by payalsin** [comment]
@caphrim007 - still getting error:
```
- name: Configure SELF-IPs on the BIG-IP
    bigip_selfip:
     server: "10.192.73.218"
     user: "admin"
     password: "admin"
     validate_certs: False
     name: "selfip"
     address: "10.158.68.10"
     netmask: "255.255.255.0"
     vlan: "/Common/External"
     partition: "Tenant1A"
     traffic_group: "/Common/traffic-group-local-only"
    delegate_to: localhost

```
fatal: [10.192.73.218 -> localhost]: FAILED! => {"changed": false, "failed": true, "msg": "400 Unexpected Error: Bad Request for uri: https://10.192.73.218:443/mgmt/tm/net/self/\nText: u'{\"code\":400,\"message\":\"01070277:3: The requested vlan, vlangroup or tunnel (/Tenant1A/External) was not found.\",\"errorStack\":[],\"apiError\":3}'"}

**Comment by payalsin** [comment]
@caphrim007 - latest fix looks good
