### ISSUE TITLE
bigip_virtual_server NOT idempotent when a partition is specified

### ISSUE THREAD

**Issue by erjac77** [F5Networks/f5-ansible#961]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
bigip_virtual_server

##### ANSIBLE VERSION

```
ansible 2.6.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/osboxes/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### PYTHON VERSION

```
Python 2.7.12
```

##### BIGIP VERSION

```
Sys::Version
Main Package
  Product     BIG-IP
  Version     12.1.2
  Build       0.0.249
  Edition     Final
  Date        Wed Nov 30 16:04:00 PST 2016
```

##### LIBRARY VERSIONS

```
f5-sdk==3.0.20
```

##### OS / ENVIRONMENT

```
Linux osboxes 4.4.0-131-generic #157-Ubuntu SMP Thu Jul 12 15:51:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

##### SUMMARY

`bigip_virtual_server` module always returns `"changed": true` when a partition other than `Common` is specified.

##### STEPS TO REPRODUCE

**Idempotent**
```
    - name: Create HTTP to HTTPS Redirection Virtual Server
      bigip_virtual_server:
        provider:
          server: "{{ ansible_host }}"
          user: "{{ http_user }}"
          password: "{{ http_pass }}"
          server_port: "{{ http_port }}"
          validate_certs: false
        name: http_to_https_redirect_virtual
        partition: Common
        description: HTTP to HTTPS Redirection Virtual
        destination: 10.10.10.10
        port: 80
        profiles:
          - tcp
          - http
        irules:
          - /Common/_sys_https_redirect
        state: present
      delegate_to: localhost
```

**NOT Idempotent**
```
    - name: Create HTTP to HTTPS Redirection Virtual Server
      bigip_virtual_server:
        provider:
          server: "{{ ansible_host }}"
          user: "{{ http_user }}"
          password: "{{ http_pass }}"
          server_port: "{{ http_port }}"
          validate_certs: false
        name: http_to_https_redirect_virtual
        partition: Test
        description: HTTP to HTTPS Redirection Virtual
        destination: 10.10.10.10
        port: 80
        profiles:
          - tcp
          - http
        irules:
          - /Common/_sys_https_redirect
        state: present
      delegate_to: localhost
```

##### EXPECTED RESULTS

If there was no changes to the resource, then ansible module should return `"changed": false`.

##### ACTUAL RESULTS

The return status is always `"changed": true`, even if there was no changes to the resource.

```
    changed: [my-big-ip -> localhost] => {
        "address_translation": false,
        "changed": true,
        "description": "HTTP to HTTPS Redirection Virtual",
        "destination": "10.10.10.10",
        "invocation": {
            "module_args": {
                "address_translation": null,
                "default_persistence_profile": null,
                "description": "HTTP to HTTPS Redirection Virtual",
                "destination": "10.10.10.10",
                "disabled_vlans": null,
                "enabled_vlans": null,
                "fallback_persistence_profile": null,
                "firewall_enforced_policy": null,
                "firewall_staged_policy": null,
                "ip_protocol": null,
                "irules": [
                    "/Common/_sys_https_redirect"
                ],
                "metadata": null,
                "name": "http_to_https_redirect_virtual",
                "partition": "Test",
                "password": null,
                "policies": null,
                "pool": null,
                "port": "80",
                "port_translation": null,
                "profiles": [
                    "tcp",
                    "http"
                ],
                "provider": {
                    "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                    "server": "x.x.x.x",
                    "server_port": 443,
                    "ssh_keyfile": null,
                    "timeout": null,
                    "transport": "rest",
                    "user": "someuser",
                    "validate_certs": false
                },
                "security_log_profiles": null,
                "server": null,
                "server_port": null,
                "snat": null,
                "source": null,
                "state": "present",
                "transport": null,
                "type": "standard",
                "user": null,
                "validate_certs": null
            }
        },
        "irules": [
            "/Common/_sys_https_redirect"
        ],
        "port": 80,
        "port_translation": false,
        "profiles": [
            {
                "context": "all",
                "fullPath": "/Test/tcp",
                "name": "tcp"
            },
            {
                "context": "all",
                "fullPath": "/Test/http",
                "name": "http"
            }
        ],
        "type": "standard"
    }
```

**Comment by erjac77** [comment]
After further testing, I thing the problem is related to the profiles. If I remove them, the playbook passed the idempotency test. I tried all sort of combinations, but without success.

```
  profiles:
    - tcp
    - http
```
```
  profiles:
    - /Common/tcp
    - /Common/http
```
```
  profiles:
    - {name: tcp, partition: Common, context: all}
    - {name: http, partition: Common, context: all}
```

**Comment by caphrim007** [comment]
@erjac77 this is a bug. The correct syntax for your use case should be 

```
  profiles:
    - /Common/tcp
    - /Common/http
```

The reason is because when you specify a `partition`, that partition is used for **all** places that a partition is needed (in this case `profiles`). The method for overriding that is to specify the specific partition where needed (as you've done in the second case).

**Comment by erjac77** [comment]
@caphrim007 , thx for your response.

However, I still get a `"changed": true` status. See below.

```
    changed: [my-big-ip -> localhost] => {
        "address_translation": false,
        "changed": true,
        "description": "HTTP to HTTPS Redirection Virtual",
        "destination": "10.10.10.10",
        "invocation": {
            "module_args": {
                "address_translation": null,
                "default_persistence_profile": null,
                "description": "HTTP to HTTPS Redirection Virtual",
                "destination": "10.10.10.10",
                "disabled_vlans": null,
                "enabled_vlans": null,
                "fallback_persistence_profile": null,
                "firewall_enforced_policy": null,
                "firewall_staged_policy": null,
                "ip_protocol": null,
                "irules": [
                    "/Common/_sys_https_redirect"
                ],
                "metadata": null,
                "name": "http_to_https_redirect_virtual",
                "partition": "Test",
                "password": null,
                "policies": null,
                "pool": null,
                "port": "80",
                "port_translation": null,
                "profiles": [
                    "/Common/tcp",
                    "/Common/http"
                ],
                "provider": {
                    "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                    "server": "x.x.x.x",
                    "server_port": 443,
                    "ssh_keyfile": null,
                    "timeout": null,
                    "transport": "rest",
                    "user": "someuser",
                    "validate_certs": false
                },
                "security_log_profiles": null,
                "server": null,
                "server_port": null,
                "snat": null,
                "source": null,
                "state": "present",
                "transport": null,
                "type": "standard",
                "user": null,
                "validate_certs": null
            }
        },
        "irules": [
            "/Common/_sys_https_redirect"
        ],
        "port": 80,
        "port_translation": false,
        "profiles": [
            {
                "context": "all",
                "fullPath": "/Common/tcp",
                "name": "/Common/tcp"
            },
            {
                "context": "all",
                "fullPath": "/Common/http",
                "name": "/Common/http"
            }
        ],
        "type": "standard"
    }
```

I think the problem is due to the fact that the partition being included in the profile's name.

```
        "profiles": [
            {
                "context": "all",
                "fullPath": "/Common/tcp",
                "name": "/Common/tcp" <----- here
            },
            {
                "context": "all",
                "fullPath": "/Common/http",
                "name": "/Common/http" <----- here
            }
        ]
```

If you look on the BIG-IP, the partition is not part of the name, but has its own parameter.

https://x.x.x.x/mgmt/tm/ltm/virtual/~Test~http_to_https_redirect_virtual/profiles

```
{
  "kind": "tm:ltm:virtual:profiles:profilescollectionstate",
  "selfLink": "https://localhost/mgmt/tm/ltm/virtual/~Test~http_to_https_redirect_virtual/profiles?ver=12.1.2",
  "items": [
    {
      "kind": "tm:ltm:virtual:profiles:profilesstate",
      "name": "http", <----- here
      "partition": "Common", <----- here
      "fullPath": "/Common/http",
      "generation": 16421,
      "selfLink": "https://localhost/mgmt/tm/ltm/virtual/~Test~http_to_https_redirect_virtual/profiles/~Common~http?ver=12.1.2",
      "context": "all"
    },
    {
      "kind": "tm:ltm:virtual:profiles:profilesstate",
      "name": "tcp", <----- here
      "partition": "Common", <----- here
      "fullPath": "/Common/tcp",
      "generation": 16421,
      "selfLink": "https://localhost/mgmt/tm/ltm/virtual/~Test~http_to_https_redirect_virtual/profiles/~Common~tcp?ver=12.1.2",
      "context": "all"
    }
  ]
}
```

I look in the code, and I think you only retrieve these 3 keys from the API (`def profiles(self)`):
* name
* context
* fullPath

The name from the API (wihtout the partition) will simply not math the one provided as argument (with the partition).

My 2 cents :)

**Comment by caphrim007** [comment]
@erjac77 yes, I know what the problem is/was, that's exactly what I fixed. You need to use the module from this repo to get the fix.

**Comment by OliElli** [comment]
I'm getting `changed: true` while using Ansible 2.8.0.dev0

**Comment by lopf** [comment]
I can confirm that this didn't fix it for us either. If profiles are defined, it always results in `changed: true`.

**Comment by MarkCon00** [comment]
I think the problem here is that, when partition is specified, the VS is saved with profile /Common/http.

          partition: OtherPartition
          profiles:
            - http

However, when the VS is already available, it takes that information as /OtherPartion/http. Thus, it would look like there was a change. 

A possible workaround would be is to create this profile under /OtherPartion partition and use below:

          partition: OtherPartition
          profiles:
             - {name: http, partition: OtherPartition}

Can we revisit this bug?

Note: destination is also saved as /Common/x.x.x.x:port

**Comment by MarkCon00** [comment]
filed https://github.com/F5Networks/f5-ansible/issues/1408

**Comment by muhammad-rafi** [comment]
I dont if this one was sorted but I am still having an issue with a simple task and it keep showing changed: true 

Ansible = 2.9.16

- name: Create a Virtual Server
  bigip_virtual_server:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    source: "{{ item.source }}"
    destination: "{{ item.destination }}"
    port: "{{ item.port }}"
    pool: "{{ item.pool }}"
    partition: "{{ item.partition | upper }}"
    snat: "{{ item.snat }}"
    state: "{{ item.state }}"
    provider: "{{ cli }}"
  delegate_to: localhost
  with_items: "{{ virtual_server }}"
  tags: virtual_server

**Comment by dagheyman** [comment]
I'm hitting this issue as well with Ansible version 2.9.23. Is there workaround for this?

**Comment by trinaths** [comment]
@muhammad-rafi  @dagheyman - Please raise a github issue with your findings.
